CREATE DATABASE STORMBOTS_2015;
USE STORMBOTS_2015;

CREATE TABLE GAME(
    GAME_ID int AUTO_INCREMENT NOT NULL,
    YEAR int NULL,
    NAME varchar(64) NULL,
    CHAMPIONSHIP_LOCATION varchar(128) NULL,
    NOTES varchar(512) NULL,
    PRIMARY KEY (GAME_ID)
);

CREATE TABLE COMPETITION(
    COMPETITION_ID int AUTO_INCREMENT NOT NULL,
    CURRENT int(1) NULL,
    GAME_ID int NOT NULL,
    COMPETITION_ORDER int NOT NULL,
    CITY varchar(64) NULL,
    STATE varchar(2) NULL,
    NAME varchar(128) NULL,
	URL varchar(4096) NULL,
	CURRENT_ROUND int(3) NULL,
    PRIMARY KEY (COMPETITION_ID)
);

CREATE TABLE TEAM(
    TEAM_ID int AUTO_INCREMENT NOT NULL,
    TEAM_NUMBER varchar(16) NOT NULL,
    TEAM_NAME varchar(64) NULL,
    SCHOOL varchar(64) NULL,
    CITY varchar(64) NULL,
    STATE varchar(2) NULL,
    LEADER varchar(64) NULL,
    YEAR_FOUNDED int NULL,
    NOTES varchar(512) NULL,
    PRIMARY KEY (TEAM_ID)
);

CREATE TABLE ROUND(
    ROUND_ID int AUTO_INCREMENT NOT NULL,
    COMPETITION_ID int NOT NULL,
    NUMBER varchar(3) NULL,
    
    RED_1_ID int(4) null,
    RED_2_ID int(4) null,
    RED_3_ID int(4) null,
    BLUE_1_ID int(4) null,
    BLUE_2_ID int(4) null,
    BLUE_3_ID int(4) null,
    
    RED_1_NUMBER int(4) null,
    RED_2_NUMBER int(4) null,
    RED_3_NUMBER int(4) null,
    BLUE_1_NUMBER int(4) null,
    BLUE_2_NUMBER int(4) null,
    BLUE_3_NUMBER int(4) null,
    
    SCORE_BLUE int(3) NULL,
    SCORE_RED int(3) NULL,
    NOTES varchar(512) NULL,
    PRIMARY KEY (ROUND_ID)
);

CREATE TABLE ROBOT(
    ROBOT_ID int AUTO_INCREMENT NOT NULL,
    TEAM_ID int NOT NULL,
    GAME_ID int NOT NULL,
    DRIVE_TRAIN varchar(256) NULL,
    DRIVE_TRAIN_MOTORS_NUMBER int(2) NULL,
    DRIVE_TRAIN_MOTORS_TYPES varchar(64) NULL,
    OTHER_MOTORS_NUMBER int(2) NULL,
    OTHER_MOTORS_TYPES varchar(64) NULL,
    WEIGHT int(3) NULL,
    PROGRAM_LANGUAGE varchar(64) NULL,
    AUTONOMOUS int(1) NULL,
    HTML_VIEW varchar(256) NULL,
    NOTES varchar(512) NULL,
    PICTURE mediumblob NULL,
    WATCHING int(3) NULL,
    PRIMARY KEY (ROBOT_ID)
);

CREATE TABLE SCORE(
	SCORE_ID int AUTO_INCREMENT NOT NULL,
    ROUND_ID int NOT NULL,
    TEAM_ID int NOT NULL,
	STAGE int(1) NOT NULL,
	POS_X int(3) NULL,
	POS_Y int(3) NULL,
	
	YELLOW_ZONE_PLACEMENT int(1) NULL,
	ROBOT_PLACEMENT int(1) NULL,
	
	PICK_UP_YELLOW int(1) NULL,
	FAIL_YELLOW int(1) NULL,
	STACK_YELLOW int(1) NULL,
	PICK_UP_CONTAINER int(1) NULL,
	FAIL_CONTAINER int(1) NULL,
	STACK_CONTAINER int(1) NULL,
	
	AUTO_ZONE int(1) NULL,
	
	PICK_UP_GRAY int(1) NULL,
	FAIL_GRAY int(1) NULL,
	STACK_GRAY int(1) NULL,
	PICK_UP_LITTER int(1) NULL,
	FAIL_LITTER int(1) NULL,
	SCORE_LITTER int(1) NULL,
	
	KNOCK_TOTE_ROBOT int(1) NULL,
	KNOCK_LITTER_ROBOT int(1) NULL,
	KNOCK_CONTAINER_ROBOT int(1) NULL,
	KNOCK_TOTE_STACK int(1) NULL,
	KNOCK_LITTER_STACK int(1) NULL,
	KNOCK_CONTAINER_STACK int(1) NULL,
	STUCK int(1) NULL,
	FOUL int(1) NULL,
	YELLOW_CARD int(1) NULL,
	RED_CARD int(1) NULL,
	
	STAR int(1) NULL,
	
	PRIMARY KEY (SCORE_ID)
);

CREATE TABLE ROBOT_DETAILS(
	ROBOT_DETAILS_ID int AUTO_INCREMENT NOT NULL,
	ROBOT_ID int NOT NULL,

	AUTO_PICK_UP_TOTE int(1) NULL,
	AUTO_PICK_UP_CONTAINER int(1) NULL,
	AUTO_CAN_STACK_TOTE int(1) NULL,
	AUTO_CAN_STACK_CONTAINER int(1) NULL,
	AUTO_MOVE_TO_AUTOZONE int(1) NULL,

	PICK_UP_TOTE int(1) NULL,
	PICK_UP_CONTAINER int(1) NULL,
	PICK_UP_LITTER int(2) NULL,

	TOTE_STORAGE int(2) NULL,
	CONTAINER_STORAGE int(2) NULL,
	LITTER_STORAGE int(2) NULL,

	CAN_CHUTE_TOTE int(1) NULL,
	CAN_CHUTE_LITTER int(1) NULL,

	STACK_TOTE int(1) NULL,
	CAN_STACK_CONTAINER int(1) NULL,
	CAN_STACK_LITTER int(1) NULL,

	STACK_COOP int(1) NULL,

	NOTES varchar(512) NULL,
	PRIMARY KEY (ROBOT_DETAILS_ID)
);
	
	

